spring:
  data:
  mondodb:
    uri:'mongodb://localhost:27017/dev-payment'

server:
  port: 8081
  shutdown: GRACEFUL


logging:
  newRelic:
    appender:
      enabled: ${NEW_RELIC_APPENDER_ENABLE:true}
  level:
    ROOT: ${LOG_ROOT_LEVEL:INFO}